### ISSUE TITLE
Reflection text + Lighthouse results

### ISSUE THREAD

**Issue by elizaveta-sergejevna** [sivanmah/sunshine-amigos#10]
One page of reflection on your solutions and the process that lead you to them, you should also reflect on what you can improve further in order to delvier a better Assignment 3.

In the same document you should attach a screenshot of the Lighthouse results in Performance/Accessibility/Best Practices/SEO (the Lighthouse results itself is not graded, but yoou have to make a screenshot).

**Comment by williambaardvik** [comment]
Starter på denne
