### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#11]
Assign yourself to this issue if you want to work on it.
Make sure you work on a branch seperate from the main branch, and open a pull request when ready to merge.

**Comment by sivanmah** [comment]
får starte med denne mens jeg prøver meg gjennom git 😄

**Comment by sivanmah** [comment]
Burde vi ha en tittel på toppen av siden som ikke endrer seg og bare sier "Favorite Color" eller noe sånt? For å hjelpe med SEO.
