### ISSUE TITLE
Apples prevent leaves from changing color

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#18]
I see there's an issue where the apples on the tree prevents the leaves from changing colors. Maybe deleting the leaves from the apples.svg would fix this issue?

**Comment by elizaveta-sergejevna** [comment]
Aha, okay, I'll see what I can do.

**Comment by elizaveta-sergejevna** [comment]
I've added an SVG of the apples without the leaves in the assets/img folder in the animation branch. Please test the animation with this, if possible.

**Comment by OlaHulleberg** [comment]
That seems to have solved it! @elizaveta-sergejevna 

Commit: 1aaf74b93672d82ec5e607c6d6b916620c4159f6
