### ISSUE TITLE
Improve CSS architecture and general CSS cleanup

### ISSUE THREAD

**Issue by elizaveta-sergejevna** [sivanmah/sunshine-amigos#22]
Before submitting the final version of the project, the following points should be implemented:

* *Separation of concerns* and better **folder structure**. https://aniweyn.github.io/advanced_css/#/lectures/lecture02

* Create partial files *_colors.scss / _fonts.scss* etc, depend on your project

* Use **BEM** naming convention

* Improve use of CSS Grid and Flex *(no grid inside flex)*

**Comment by elizaveta-sergejevna** [comment]
I talked with Sabina via e-mail and got this comment, among other things:

*So there is no need to create a folder for scss and css. Where is your index.scss.map file? How your group is compiling index.scss file?*

@OlaHulleberg, I believe you decided that we should compile our SCSS in some fancy manner! :grimacing: Please take this comment into account :cowboy_hat_face:

**Comment by OlaHulleberg** [comment]
Well, my thoughts behind having a css and scss folder (As well as not including the .map) was basically just to reduce clutter and organize the project, but I can change it, no worries.

**Comment by elizaveta-sergejevna** [comment]
I mean, I don't know what's best, I just thought I'd point out the comment from Sabina. If you think we should do it the way you initially thought, I'm sure we can, we just have to explain it somewhere when we deliver the project (I'm assuming) :clown_face:

**Comment by OlaHulleberg** [comment]
@elizaveta-sergejevna I've set up a pull request ( #23 ) to deal with the aforementioned tasks.
Please contribute and check the marks @elizaveta-sergejevna @sivanmah @williambaardvik

**Comment by OlaHulleberg** [comment]
With the recent approval of PR #23, do we consider this issue solved?
@elizaveta-sergejevna @williambaardvik @sivanmah

**Comment by elizaveta-sergejevna** [comment]
To me it seems that way. Close it up!

**Comment by williambaardvik** [comment]
yup!
