### ISSUE TITLE
Urgent: Readme

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#28]
I realise we haven't described the project at all in the README, fix ASAP.

**Comment by OlaHulleberg** [comment]
I have created a description [branch](https://github.com/sivanmah/sunshine-amigos/tree/description) where you can push the changes.

**Comment by elizaveta-sergejevna** [comment]
Describing the project like we did in the reflection text for the first assignment or like for the presentation?

**Comment by OlaHulleberg** [comment]
The first one. Explain what and why we're doing this.
