### ISSUE TITLE
CSS - Too many files

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#4]
As per stated in the documentation:
>To avoid making our files too long, we think it's best to split them up in specific categories, for example by having one scss/css-file for the web page itself and another one for the different animations (and so on). This way we don't have to look through hundreds of lines of code in one single file and can instead group necessary styles/structures/scripts together in smaller amounts.

I believe this is a good idea, however having a file for each animation would make the project tedious to work with. Maybe having one animations.css would suit it better?

Share your thoughts on this

**Comment by elizaveta-sergejevna** [comment]
Yes, that's what I meant. Not one file for each animation, but one file for different categories of code.

**Comment by OlaHulleberg** [comment]
Alright, then it should be all good!
