### ISSUE TITLE
Finalize page design, and work on details.

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#6]
Assign yourself to this issue if you want to work on it.
Make sure you work on a branch seperate from the main branch, and open a pull request when ready to merge.

**Comment by OlaHulleberg** [comment]
Positioning of tree, tree colors, text colors, text positioning, text spacing and whatever falls under the 'page-design' category.
Feel free to work on anything like that here, just make sure you assign yourself to this issue and communicate what you're working on in this issue/thread!

**Comment by OlaHulleberg** [comment]
Do we consider this issue solved, or is there more work to be done? @elizaveta-sergejevna @williambaardvik

**Comment by elizaveta-sergejevna** [comment]
I've been working with the page as it is for a while now and it seems fine on my end, although from the few screenshots you've shared, @OlaHulleberg, it seems that your viewport is bigger than mine and so the elements and their position look a bit different. But I don't think it's that big of a deal. Unless the rest of you guys see something that needs changing, I hope we can consider us done with this.
