### ISSUE TITLE
Responsive design (Mobile and so on)

### ISSUE THREAD

**Issue by OlaHulleberg** [sivanmah/sunshine-amigos#8]
Assign yourself to this issue if you want to work on it.
Make sure you work on a branch seperate from the main branch, and open a pull request when ready to merge.

**Comment by OlaHulleberg** [comment]
We need media queries for screens of 'unusual proportions', and smaller sizes like mobile. Make sure you follow the story board when working on this!

**Comment by sivanmah** [comment]
Will try this. Anything i have to keep in mind regarding the animations when im making the screen smaller?

**Comment by OlaHulleberg** [comment]
Not really, as long as it looks like the storyboard.

**Comment by sivanmah** [comment]
I believe the media queries should be enough to make the page responsive for mobile devices. Please take a look at the responsive branch and notify me if there is anything you believe is missing or should be changed.
